### ISSUE TITLE
Fix calculateAverage bug to update DOM

### ISSUE THREAD

**Issue by nvalentini21** [maddielaw/FitLit#4]
Currently, the method from the User Repository class displays "NaN" and should display the average steps for all users on the activity card when being called in scripts.js.

**Comment by maddielaw** [comment]
Refactored calculateAverageStepGoal() function in UserRepository class. Moved the divide by array length outside of the loop to the final return. Refactored function passes all existing tests and is now able to update the DOM successfully.
